function [fitresult, gof] = createFit(X, Y, SCO_700eV)
%CREATEFIT(X,Y,SCO_700EV)
%  Create a fit.
%
%  Data for 'SCO700eV_3Dfit' fit:
%      X Input : X
%      Y Input : Y
%      Z Output: SCO_700eV
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 19-Jan-2021 18:17:06


%% Fit: 'SCO700eV_3Dfit'.
[xData, yData, zData] = prepareSurfaceData( X, Y, SCO_700eV );

% Set up fittype and options.
ft = fittype( 'poly22' );

% Fit model to data.
[fitresult, gof] = fit( [xData, yData], zData, ft );

% Plot fit with data.
figure( 'Name', 'SCO700eV_3Dfit' );
h = plot( fitresult, [xData, yData], zData );
legend( h, 'SCO700eV_3Dfit', 'SCO_700eV vs. X, Y', 'Location', 'NorthEast', 'Interpreter', 'none' );
% Label axes
xlabel( 'X', 'Interpreter', 'none' );
ylabel( 'Y', 'Interpreter', 'none' );
zlabel( 'SCO_700eV', 'Interpreter', 'none' );
grid on


