function S = sumNN3D(spins, i, j, k)
%{
sums the six nearest neighbors in 3D

%}
S = spins((i-1), j, k) +...
    spins((i+1), j, k) +...
    spins(i, (j-1), k) +...
    spins(i, (j+1), k) +...
    spins(i, j, (k+1)) +...
    spins(i, j, (k-1));
end