function S = sumNNN3D_ZmagField(spins, i, j, k, weights, periodic, z)
%{

%}

[M, N, ~] = size(spins);
sNN_wt = weights(1);
sNNN_wt = weights(2);
sNNNN_wt = weights(3);

if periodic
    
    % set up for 2D only right now
    V = mod(M+i-2, M);
    if V == 0
        V = M;
    end
    W = mod(M+i-1, M);
    if W == 0
        W = M;
    end
    X = i;
    Y = mod(M+i+1, M);
    if Y == 0
        Y = M;
    end
    Z = mod(M+i+2, M);
    if Z == 0
        Z = M;
    end
    
    A = mod(N+j-2, N);
    if A == 0
        A = N;
    end
    B = mod(N+j-1, N);
    if B  == 0
        B = N;
    end
    
    C = j;
    D = mod(N+j+1, N);
    if D == 0
        D = N;
    end
    E = mod(N+j+2, N);
    if E == 0
        E = N;
    end
    
    sNN = spins(X, D, k) +...
        spins(Y, C, k) +...
        spins(W, C, k) +...
        spins(X, B, k) +...
        z*spins(i, j, (k+1)) +...
        z*spins(i, j, (k-1));
    
    sNN = spins(Y, D, k) +...
        spins(W, D, k) +...
        spins(Y, B, k) +...
        spins(W, B, k) +...
        z*spins(i, j, (k+1)) +...
        z*spins(i, j, (k-1));
    
    sNNN = spins(W, B, k)+...
        spins(W, D, k)+...
        spins(Y, B, k)+...
        spins(Y, D, k)+...
        z*spins(W, j, k-1)+...
        z*spins(W, j, k+1)+...
        z*spins(Y, j, k-1)+...
        z*spins(Y, j, k+1)+...
        z*spins(i, B, k-1)+...
        z*spins(i, B, k+1)+...
        z*spins(i, D, k-1)+...
        z*spins(i, D, k+1);
    
    sNNNN = z*spins(Y, D, k+1)+...
        z*spins(Y, D, k-1)+...
        z*spins(Y, B, k+1)+...
        z*spins(Y, B, k-1)+...
        z*spins(W, D, k+1)+...
        z*spins(W, D, k-1)+...
        z*spins(W, B, k+1)+...
        z*spins(W, B, k-1);
    
else
    
    sNN = spins((i-1), j, k) +...
        spins((i+1), j, k) +...
        spins(i, (j-1), k) +...
        spins(i, (j+1), k) +...
        z*spins(i, j, (k+1)) +...
        z*spins(i, j, (k-1));
    
    sNNN = spins(i-1, j-1, k)+...
        spins(i-1, j+1, k)+...
        z*spins(i-1, j, k-1)+...
        z*spins(i-1, j, k+1)+...
        spins(i+1, j-1, k)+...
        spins(i+1, j+1, k)+...
        z*spins(i+1, j, k-1)+...
        z*spins(i+1, j, k+1)+...
        z*spins(i, j-1, k-1)+...
        z*spins(i, j-1, k+1)+...
        z*spins(i, j+1, k-1)+...
        z*spins(i, j+1, k+1);
    
    sNNNN = z*spins(i+1, j+1, k+1)+...
        z*spins(i+1, j+1, k-1)+...
        z*spins(i+1, j-1, k+1)+...
        z*spins(i+1, j-1, k-1)+...
        z*spins(i-1, j+1, k+1)+...
        z*spins(i-1, j+1, k-1)+...
        z*spins(i-1, j-1, k+1)+...
        z*spins(i-1, j-1, k-1);
end
S = sNN_wt*sNN + sNNN_wt*sNNN + sNNNN_wt*sNNNN;

end