function S = sumNNN3D(spins, i, j, k, weights)
%{

%}

[m, n, p] = size(spins);
sNN_wt = weights(1);
sNNN_wt = weights(2);
sNNNN_wt = weights(3);


sNN = spins((i-1), j, k) +...
    spins((i+1), j, k) +...
    spins(i, (j-1), k) +...
    spins(i, (j+1), k) +...
    spins(i, j, (k+1)) +...
    spins(i, j, (k-1));

sNNN = spins(i-1, j-1, k)+...
    spins(i-1, j+1, k)+...
    spins(i-1, j, k-1)+...
    spins(i-1, j, k+1)+...
    spins(i+1, j-1, k)+...
    spins(i+1, j+1, k)+...
    spins(i+1, j, k-1)+...
    spins(i+1, j, k+1)+...
    spins(i, j-1, k-1)+...
    spins(i, j-1, k+1)+...
    spins(i, j+1, k-1)+...
    spins(i, j+1, k+1);

sNNNN = spins(i+1, j+1, k+1)+...
    spins(i+1, j+1, k-1)+...
    spins(i+1, j-1, k+1)+...
    spins(i+1, j-1, k-1)+...
    spins(i-1, j+1, k+1)+...
    spins(i-1, j+1, k-1)+...
    spins(i-1, j-1, k+1)+...
    spins(i-1, j-1, k-1);

S = sNN_wt*sNN + sNNN_wt*sNNN + sNNNN_wt*sNNNN;

end